hw-01
OlenaSavchenko/nodejs pull request #1
Opened 2020-09-07 09:42 UTC by OlenaSavchenko

2020-09-07 09:56 UTC, odykyi commented on db/contacts.js
> +  fs.writeFile(contactsPath, JSON.stringify(contactsData));
await

2020-09-07 09:58 UTC, odykyi commented on db/contacts.js
> +  fs.writeFile(contactsPath, JSON.stringify(result));
await

2020-09-07 10:49 UTC, odykyi requested changes
comments

2020-09-12 09:42 UTC, OlenaSavchenko commented on db/contacts.js
> +  fs.writeFile(contactsPath, JSON.stringify(contactsData));
мы к каждому методу добавляем await чтобы операция выполнялась асинхронно?
и к push и к writeFile?

2020-09-14 06:50 UTC, odykyi approved these changes

2020-09-14 06:52 UTC, merged